version: '3.1'

services:
  db:
    image: mysql
    container_name: jpa_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - jpa_mysql_vol:/var/lib/mysql

volumes:
  jpa_mysql_vol: