CREATE TABLE comment (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    review_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
);