version: '3.1'

services:
  db:
    image: mysql
    container_name: jdnd
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - jdnd:/var/lib/mysql

volumes:
  jdnd: