pipeline {
    agent any
    environment {
        PROJECT_DIRECTORY = "part05/module01/projects/auth-course/"
    }

    stages {
        stage ('Start') {
            steps {
                echo 'Started pipeline'
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn -f $PROJECT_DIRECTORY -B -DskikpTests clean package'
            }
        }
        stage ('Test') {
            steps {
                sh 'mvn -f $PROJECT_DIRECTORY test'
            }
        }
        stage ('Image') {
            steps {
                sh 'ssh vagrant@172.20.1.20 "bash /home/vagrant/script-build.sh;exit;"2>&1'
            }
        }
    }
}