pipeline {
    agent any

    stages {
        stage ('Start') {
            steps {
                echo 'Started pipeline'
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn -B -DskikpTests clean package'
            }
        }
    }
}