pipeline {
    agent any
    environment {
        PROJECT_DIRECTORY = "part05/module01/projects/auth-course/"
    }

    stages {
        stage ('Start') {
            steps {
                echo 'Started pipeline'
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn -f $PROJECT_DIRECTORY -B -DskikpTests clean package'
            }
        }
        stage ('Test') {
            steps {
                sh 'mvn -f $PROJECT_DIRECTORY test'
            }
        }
    }
}