version: "3.1"

services:
  db_mysql:
    image: mysql
    container_name: mysql_midterm
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3006"
    volumes:
      - vol_midterm:/var/lib/mysql

volumes:
  vol_midterm:
