PRIVATE_KEY = "~/.ssh/lab"
PUBLIC_KEY  = "~/.ssh/lab.pub"

machines = {
    "fake-aws-ec2" => {"memory" => "2048", "cpu" => "2", "ip" => "20", "image" => "ubuntu/jammy64"},
}

Vagrant.configure("2") do |config|
    
    machines.each do |name, conf|
        config.vm.define "#{name}" do |machine|
            machine.ssh.insert_key = false
            machine.ssh.private_key_path = [PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
            machine.vm.provision "file", source: PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

            machine.vm.box = "#{conf["image"]}"
            machine.vm.hostname = "#{name}"
            machine.vm.network "private_network", ip: "172.20.1.#{conf["ip"]}"
            machine.vm.provider "virtualbox" do |vb|
                vb.name = "#{name}"
                vb.cpus = conf["cpu"]
                vb.memory = conf["memory"]
            end
        end
    end
end
